export default {
    background: "#F3FAF4",
    textPrimary: "#000",
    textSecondary: "#204728",
    textTernary: "#0F0F0F",
    textDimSubTitle: "#5e5e5e",
    textPopup: "#bbbbbb",
    buttonBackground: "#016A70",
    iconColor: "#000",
    questionBg: "#F3FAF4",
    answerTab: "#fff",
    modalBackground: "rgba(0, 0, 0, 0.5)",
    loadingModalBackground: "#fff",
    resultTabCurve: "#fff",
    resultBg: "#fff",
    resultContaineBg: "#F3FAF4",
    selectedTab: "#c5dcde",
    buttonText: "#fff",
    semi_container: "#fff",
    dimText: "#9A9A9A",
    imageBG: "#F3FAF4",
    googleSignButtonText: "#EEEEEE",
    googleStartButtonText: "#016A70",
    skipButtonBackground: "#5E5E5E",
    skipButtonText: "#fff",
    title: "#016A70",
    border: "#ccc",
    dot: "#121212",
    darkBG: "#fff",
    activeDot: "#016A70",
    imageStyle: {
        opacity: 1, // Normal brightness in light mode
    },

    tabBg: "#fff",
    tabActiveColor: "#C5F4D3",
    tabActiveIcon: "#016A70",
    tabInactive: "#000",

    bgColorPopup: "rgba(255, 255, 255, 0.95)",
    warningText: "#ff0000",

    landingSubTextContainer: "#F3FAF4",
    landingInstruction: "#333",
    landingListItem: "#555",
    childLottieCircle: "rgba(1, 106, 112, 0.1)",
    childModal: "#F3FAF4",
    childModalContent: "",
    ChildMidShadow: 5
};
